## Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Links and Build
email: jjackson0014@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Sharing knowledge
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jjackson0014.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: jjackson0014.github.io
instagram_username: linksandbuild_
github_username:  jjackson0014

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown

# Collection Configuration
collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default_layout"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
